title: sukan0204's github page
author: sukan0204
email: sukan0204@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Not much to describe yet
theme: minima
# social links
twitter_username: sukan0204 # DO NOT include the @ character, or else the build will fail!
github_username:  sukan0204 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
